# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ScheduleService_pb2 as ScheduleService__pb2
from Share import Type_pb2 as Share_dot_Type__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


class ScheduleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddHoliday = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/AddHoliday',
        request_serializer=ScheduleService__pb2.EditHolidayRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.EditHolidayResponse.FromString,
        )
    self.RemoveHoliday = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/RemoveHoliday',
        request_serializer=ScheduleService__pb2.EditHolidayRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.EditHolidayResponse.FromString,
        )
    self.AddSchedule = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/AddSchedule',
        request_serializer=ScheduleService__pb2.EditQuoteScheduleRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.EditQuoteScheduleResponse.FromString,
        )
    self.RemoveSchedule = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/RemoveSchedule',
        request_serializer=ScheduleService__pb2.EditQuoteScheduleRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.EditQuoteScheduleResponse.FromString,
        )
    self.UpdateSchedule = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/UpdateSchedule',
        request_serializer=ScheduleService__pb2.EditQuoteScheduleRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.EditQuoteScheduleResponse.FromString,
        )
    self.GetSchedule = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/GetSchedule',
        request_serializer=ScheduleService__pb2.GetScheduleRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.GetScheduleResponse.FromString,
        )
    self.GetScheduleUpdateTime = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/GetScheduleUpdateTime',
        request_serializer=Share_dot_Type__pb2.EmptyRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.FromString,
        )
    self.GetScheduleList = channel.unary_unary(
        '/QuoteResearch.Service.ScheduleService.ScheduleService/GetScheduleList',
        request_serializer=Share_dot_Type__pb2.EmptyRequest.SerializeToString,
        response_deserializer=ScheduleService__pb2.GetQuoteScheduleListResponse.FromString,
        )


class ScheduleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddHoliday(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveHoliday(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddSchedule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RemoveSchedule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateSchedule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSchedule(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetScheduleUpdateTime(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetScheduleList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScheduleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddHoliday': grpc.unary_unary_rpc_method_handler(
          servicer.AddHoliday,
          request_deserializer=ScheduleService__pb2.EditHolidayRequest.FromString,
          response_serializer=ScheduleService__pb2.EditHolidayResponse.SerializeToString,
      ),
      'RemoveHoliday': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveHoliday,
          request_deserializer=ScheduleService__pb2.EditHolidayRequest.FromString,
          response_serializer=ScheduleService__pb2.EditHolidayResponse.SerializeToString,
      ),
      'AddSchedule': grpc.unary_unary_rpc_method_handler(
          servicer.AddSchedule,
          request_deserializer=ScheduleService__pb2.EditQuoteScheduleRequest.FromString,
          response_serializer=ScheduleService__pb2.EditQuoteScheduleResponse.SerializeToString,
      ),
      'RemoveSchedule': grpc.unary_unary_rpc_method_handler(
          servicer.RemoveSchedule,
          request_deserializer=ScheduleService__pb2.EditQuoteScheduleRequest.FromString,
          response_serializer=ScheduleService__pb2.EditQuoteScheduleResponse.SerializeToString,
      ),
      'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateSchedule,
          request_deserializer=ScheduleService__pb2.EditQuoteScheduleRequest.FromString,
          response_serializer=ScheduleService__pb2.EditQuoteScheduleResponse.SerializeToString,
      ),
      'GetSchedule': grpc.unary_unary_rpc_method_handler(
          servicer.GetSchedule,
          request_deserializer=ScheduleService__pb2.GetScheduleRequest.FromString,
          response_serializer=ScheduleService__pb2.GetScheduleResponse.SerializeToString,
      ),
      'GetScheduleUpdateTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetScheduleUpdateTime,
          request_deserializer=Share_dot_Type__pb2.EmptyRequest.FromString,
          response_serializer=google_dot_protobuf_dot_timestamp__pb2.Timestamp.SerializeToString,
      ),
      'GetScheduleList': grpc.unary_unary_rpc_method_handler(
          servicer.GetScheduleList,
          request_deserializer=Share_dot_Type__pb2.EmptyRequest.FromString,
          response_serializer=ScheduleService__pb2.GetQuoteScheduleListResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'QuoteResearch.Service.ScheduleService.ScheduleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
