# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from Share import Type_pb2 as Share_dot_Type__pb2
import StrategyService_pb2 as StrategyService__pb2


class StrategyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetStrategyInfo = channel.unary_unary(
        '/QuoteResearch.Service.StrategyService.StrategyService/GetStrategyInfo',
        request_serializer=StrategyService__pb2.GetStrategyInfoRequest.SerializeToString,
        response_deserializer=StrategyService__pb2.GetStrategyInfoResponse.FromString,
        )
    self.GetStrategyList = channel.unary_unary(
        '/QuoteResearch.Service.StrategyService.StrategyService/GetStrategyList',
        request_serializer=Share_dot_Type__pb2.EmptyRequest.SerializeToString,
        response_deserializer=StrategyService__pb2.GetStrategyListResponse.FromString,
        )
    self.GetQuoteStrategyPair = channel.unary_unary(
        '/QuoteResearch.Service.StrategyService.StrategyService/GetQuoteStrategyPair',
        request_serializer=StrategyService__pb2.GetQuoteStrategyPairRequest.SerializeToString,
        response_deserializer=StrategyService__pb2.GetQuoteStrategyPairResponse.FromString,
        )


class StrategyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetStrategyInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetStrategyList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetQuoteStrategyPair(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StrategyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetStrategyInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetStrategyInfo,
          request_deserializer=StrategyService__pb2.GetStrategyInfoRequest.FromString,
          response_serializer=StrategyService__pb2.GetStrategyInfoResponse.SerializeToString,
      ),
      'GetStrategyList': grpc.unary_unary_rpc_method_handler(
          servicer.GetStrategyList,
          request_deserializer=Share_dot_Type__pb2.EmptyRequest.FromString,
          response_serializer=StrategyService__pb2.GetStrategyListResponse.SerializeToString,
      ),
      'GetQuoteStrategyPair': grpc.unary_unary_rpc_method_handler(
          servicer.GetQuoteStrategyPair,
          request_deserializer=StrategyService__pb2.GetQuoteStrategyPairRequest.FromString,
          response_serializer=StrategyService__pb2.GetQuoteStrategyPairResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'QuoteResearch.Service.StrategyService.StrategyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
