// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommandService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuoteResearch.Service.CommandService {

  /// <summary>Holder for reflection information generated from CommandService.proto</summary>
  public static partial class CommandServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for CommandService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CommandServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRDb21tYW5kU2VydmljZS5wcm90bxIkUXVvdGVSZXNlYXJjaC5TZXJ2aWNl",
            "LkNvbW1hbmRTZXJ2aWNlGhBTaGFyZS9UeXBlLnByb3RvIigKFkNvbW1hbmRT",
            "ZXJ2aWNlUmVzcG9uc2USDgoGcmVzdWx0GAEgASgFMvYCCg5Db21tYW5kU2Vy",
            "dmljZRJ1CgVTdGFydBIuLlF1b3RlUmVzZWFyY2guU2VydmljZS5TaGFyZS5U",
            "eXBlLkVtcHR5UmVxdWVzdBo8LlF1b3RlUmVzZWFyY2guU2VydmljZS5Db21t",
            "YW5kU2VydmljZS5Db21tYW5kU2VydmljZVJlc3BvbnNlEnQKBFN0b3ASLi5R",
            "dW90ZVJlc2VhcmNoLlNlcnZpY2UuU2hhcmUuVHlwZS5FbXB0eVJlcXVlc3Qa",
            "PC5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuQ29tbWFuZFNlcnZpY2UuQ29tbWFu",
            "ZFNlcnZpY2VSZXNwb25zZRJ3CgdSZXN0YXJ0Ei4uUXVvdGVSZXNlYXJjaC5T",
            "ZXJ2aWNlLlNoYXJlLlR5cGUuRW1wdHlSZXF1ZXN0GjwuUXVvdGVSZXNlYXJj",
            "aC5TZXJ2aWNlLkNvbW1hbmRTZXJ2aWNlLkNvbW1hbmRTZXJ2aWNlUmVzcG9u",
            "c2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QuoteResearch.Service.Share.Type.TypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.CommandService.CommandServiceResponse), global::QuoteResearch.Service.CommandService.CommandServiceResponse.Parser, new[]{ "Result" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CommandServiceResponse : pb::IMessage<CommandServiceResponse> {
    private static readonly pb::MessageParser<CommandServiceResponse> _parser = new pb::MessageParser<CommandServiceResponse>(() => new CommandServiceResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CommandServiceResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.CommandService.CommandServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandServiceResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandServiceResponse(CommandServiceResponse other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CommandServiceResponse Clone() {
      return new CommandServiceResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CommandServiceResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CommandServiceResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CommandServiceResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
