// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: OrderService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace QuoteResearch.Service.OrderService {
  public static partial class OrderService
  {
    static readonly string __ServiceName = "QuoteResearch.Service.OrderService.OrderService";

    static readonly grpc::Marshaller<global::QuoteResearch.Service.OrderService.OrderRequest> __Marshaller_QuoteResearch_Service_OrderService_OrderRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::QuoteResearch.Service.OrderService.OrderRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::QuoteResearch.Service.OrderService.OrderResponse> __Marshaller_QuoteResearch_Service_OrderService_OrderResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::QuoteResearch.Service.OrderService.OrderResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::QuoteResearch.Service.OrderService.MeltDownRequest> __Marshaller_QuoteResearch_Service_OrderService_MeltDownRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::QuoteResearch.Service.OrderService.MeltDownRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse> __Method_CreateBearPosition = new grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateBearPosition",
        __Marshaller_QuoteResearch_Service_OrderService_OrderRequest,
        __Marshaller_QuoteResearch_Service_OrderService_OrderResponse);

    static readonly grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse> __Method_CreateBullPosition = new grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateBullPosition",
        __Marshaller_QuoteResearch_Service_OrderService_OrderRequest,
        __Marshaller_QuoteResearch_Service_OrderService_OrderResponse);

    static readonly grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse> __Method_CoverPosition = new grpc::Method<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CoverPosition",
        __Marshaller_QuoteResearch_Service_OrderService_OrderRequest,
        __Marshaller_QuoteResearch_Service_OrderService_OrderResponse);

    static readonly grpc::Method<global::QuoteResearch.Service.OrderService.MeltDownRequest, global::QuoteResearch.Service.OrderService.OrderResponse> __Method_MeltDown = new grpc::Method<global::QuoteResearch.Service.OrderService.MeltDownRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "MeltDown",
        __Marshaller_QuoteResearch_Service_OrderService_MeltDownRequest,
        __Marshaller_QuoteResearch_Service_OrderService_OrderResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::QuoteResearch.Service.OrderService.OrderServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of OrderService</summary>
    [grpc::BindServiceMethod(typeof(OrderService), "BindService")]
    public abstract partial class OrderServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBearPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBullPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::QuoteResearch.Service.OrderService.OrderResponse> CoverPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::QuoteResearch.Service.OrderService.OrderResponse> MeltDown(global::QuoteResearch.Service.OrderService.MeltDownRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for OrderService</summary>
    public partial class OrderServiceClient : grpc::ClientBase<OrderServiceClient>
    {
      /// <summary>Creates a new client for OrderService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public OrderServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for OrderService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public OrderServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected OrderServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected OrderServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CreateBearPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBearPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CreateBearPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateBearPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBearPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBearPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBearPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateBearPosition, null, options, request);
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CreateBullPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBullPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CreateBullPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateBullPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBullPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateBullPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CreateBullPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateBullPosition, null, options, request);
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CoverPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoverPosition(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse CoverPosition(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CoverPosition, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CoverPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CoverPositionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> CoverPositionAsync(global::QuoteResearch.Service.OrderService.OrderRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CoverPosition, null, options, request);
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse MeltDown(global::QuoteResearch.Service.OrderService.MeltDownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MeltDown(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::QuoteResearch.Service.OrderService.OrderResponse MeltDown(global::QuoteResearch.Service.OrderService.MeltDownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_MeltDown, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> MeltDownAsync(global::QuoteResearch.Service.OrderService.MeltDownRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MeltDownAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.OrderService.OrderResponse> MeltDownAsync(global::QuoteResearch.Service.OrderService.MeltDownRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_MeltDown, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override OrderServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new OrderServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(OrderServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateBearPosition, serviceImpl.CreateBearPosition)
          .AddMethod(__Method_CreateBullPosition, serviceImpl.CreateBullPosition)
          .AddMethod(__Method_CoverPosition, serviceImpl.CoverPosition)
          .AddMethod(__Method_MeltDown, serviceImpl.MeltDown).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, OrderServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateBearPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(serviceImpl.CreateBearPosition));
      serviceBinder.AddMethod(__Method_CreateBullPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(serviceImpl.CreateBullPosition));
      serviceBinder.AddMethod(__Method_CoverPosition, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QuoteResearch.Service.OrderService.OrderRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(serviceImpl.CoverPosition));
      serviceBinder.AddMethod(__Method_MeltDown, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QuoteResearch.Service.OrderService.MeltDownRequest, global::QuoteResearch.Service.OrderService.OrderResponse>(serviceImpl.MeltDown));
    }

  }
}
#endregion
