// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuoteService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace QuoteResearch.Service.QuoteService {
  public static partial class QuoteService
  {
    static readonly string __ServiceName = "QuoteResearch.Service.QuoteService.QuoteService";

    static readonly grpc::Marshaller<global::QuoteResearch.Service.Share.Type.EmptyRequest> __Marshaller_QuoteResearch_Service_Share_Type_EmptyRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::QuoteResearch.Service.Share.Type.EmptyRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::QuoteResearch.Service.QuoteService.GetQuoteListResponse> __Marshaller_QuoteResearch_Service_QuoteService_GetQuoteListResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::QuoteResearch.Service.QuoteService.GetQuoteListResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::QuoteResearch.Service.Share.Type.EmptyRequest, global::QuoteResearch.Service.QuoteService.GetQuoteListResponse> __Method_GetQuoteList = new grpc::Method<global::QuoteResearch.Service.Share.Type.EmptyRequest, global::QuoteResearch.Service.QuoteService.GetQuoteListResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetQuoteList",
        __Marshaller_QuoteResearch_Service_Share_Type_EmptyRequest,
        __Marshaller_QuoteResearch_Service_QuoteService_GetQuoteListResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::QuoteResearch.Service.QuoteService.QuoteServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of QuoteService</summary>
    [grpc::BindServiceMethod(typeof(QuoteService), "BindService")]
    public abstract partial class QuoteServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::QuoteResearch.Service.QuoteService.GetQuoteListResponse> GetQuoteList(global::QuoteResearch.Service.Share.Type.EmptyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for QuoteService</summary>
    public partial class QuoteServiceClient : grpc::ClientBase<QuoteServiceClient>
    {
      /// <summary>Creates a new client for QuoteService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public QuoteServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for QuoteService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public QuoteServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected QuoteServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected QuoteServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::QuoteResearch.Service.QuoteService.GetQuoteListResponse GetQuoteList(global::QuoteResearch.Service.Share.Type.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuoteList(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::QuoteResearch.Service.QuoteService.GetQuoteListResponse GetQuoteList(global::QuoteResearch.Service.Share.Type.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetQuoteList, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.QuoteService.GetQuoteListResponse> GetQuoteListAsync(global::QuoteResearch.Service.Share.Type.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetQuoteListAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::QuoteResearch.Service.QuoteService.GetQuoteListResponse> GetQuoteListAsync(global::QuoteResearch.Service.Share.Type.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetQuoteList, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override QuoteServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new QuoteServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(QuoteServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetQuoteList, serviceImpl.GetQuoteList).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, QuoteServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetQuoteList, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::QuoteResearch.Service.Share.Type.EmptyRequest, global::QuoteResearch.Service.QuoteService.GetQuoteListResponse>(serviceImpl.GetQuoteList));
    }

  }
}
#endregion
