// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuoteService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuoteResearch.Service.QuoteService {

  /// <summary>Holder for reflection information generated from QuoteService.proto</summary>
  public static partial class QuoteServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for QuoteService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QuoteServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJRdW90ZVNlcnZpY2UucHJvdG8SIlF1b3RlUmVzZWFyY2guU2VydmljZS5R",
            "dW90ZVNlcnZpY2UaEFNoYXJlL1R5cGUucHJvdG8aH2dvb2dsZS9wcm90b2J1",
            "Zi90aW1lc3RhbXAucHJvdG8ilgEKFEdldFF1b3RlTGlzdFJlc3BvbnNlEg4K",
            "BlJlc3VsdBgBIAEoBRIyCg5MYXN0VXBkYXRlVGltZRgCIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXASOgoJUXVvdGVMaXN0GAMgAygLMicuUXVv",
            "dGVSZXNlYXJjaC5TZXJ2aWNlLlNoYXJlLlR5cGUuUXVvdGUyiAEKDFF1b3Rl",
            "U2VydmljZRJ4CgxHZXRRdW90ZUxpc3QSLi5RdW90ZVJlc2VhcmNoLlNlcnZp",
            "Y2UuU2hhcmUuVHlwZS5FbXB0eVJlcXVlc3QaOC5RdW90ZVJlc2VhcmNoLlNl",
            "cnZpY2UuUXVvdGVTZXJ2aWNlLkdldFF1b3RlTGlzdFJlc3BvbnNlYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::QuoteResearch.Service.Share.Type.TypeReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.QuoteService.GetQuoteListResponse), global::QuoteResearch.Service.QuoteService.GetQuoteListResponse.Parser, new[]{ "Result", "LastUpdateTime", "QuoteList" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetQuoteListResponse : pb::IMessage<GetQuoteListResponse> {
    private static readonly pb::MessageParser<GetQuoteListResponse> _parser = new pb::MessageParser<GetQuoteListResponse>(() => new GetQuoteListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuoteListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.QuoteService.QuoteServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteListResponse(GetQuoteListResponse other) : this() {
      result_ = other.result_;
      lastUpdateTime_ = other.lastUpdateTime_ != null ? other.lastUpdateTime_.Clone() : null;
      quoteList_ = other.quoteList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteListResponse Clone() {
      return new GetQuoteListResponse(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "LastUpdateTime" field.</summary>
    public const int LastUpdateTimeFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastUpdateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastUpdateTime {
      get { return lastUpdateTime_; }
      set {
        lastUpdateTime_ = value;
      }
    }

    /// <summary>Field number for the "QuoteList" field.</summary>
    public const int QuoteListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::QuoteResearch.Service.Share.Type.Quote> _repeated_quoteList_codec
        = pb::FieldCodec.ForMessage(26, global::QuoteResearch.Service.Share.Type.Quote.Parser);
    private readonly pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.Quote> quoteList_ = new pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.Quote>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.Quote> QuoteList {
      get { return quoteList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuoteListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuoteListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(LastUpdateTime, other.LastUpdateTime)) return false;
      if(!quoteList_.Equals(other.quoteList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (lastUpdateTime_ != null) hash ^= LastUpdateTime.GetHashCode();
      hash ^= quoteList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (lastUpdateTime_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(LastUpdateTime);
      }
      quoteList_.WriteTo(output, _repeated_quoteList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (lastUpdateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastUpdateTime);
      }
      size += quoteList_.CalculateSize(_repeated_quoteList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuoteListResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.lastUpdateTime_ != null) {
        if (lastUpdateTime_ == null) {
          LastUpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastUpdateTime.MergeFrom(other.LastUpdateTime);
      }
      quoteList_.Add(other.quoteList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
          case 18: {
            if (lastUpdateTime_ == null) {
              LastUpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(LastUpdateTime);
            break;
          }
          case 26: {
            quoteList_.AddEntriesFrom(input, _repeated_quoteList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
