// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ScheduleService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace QuoteResearch.Service.ScheduleService {

  /// <summary>Holder for reflection information generated from ScheduleService.proto</summary>
  public static partial class ScheduleServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for ScheduleService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ScheduleServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTY2hlZHVsZVNlcnZpY2UucHJvdG8SJVF1b3RlUmVzZWFyY2guU2Vydmlj",
            "ZS5TY2hlZHVsZVNlcnZpY2UaH2dvb2dsZS9wcm90b2J1Zi90aW1lc3RhbXAu",
            "cHJvdG8aEFNoYXJlL1R5cGUucHJvdG8iggEKEkVkaXRIb2xpZGF5UmVxdWVz",
            "dBI2CgVRdW90ZRgBIAEoCzInLlF1b3RlUmVzZWFyY2guU2VydmljZS5TaGFy",
            "ZS5UeXBlLlF1b3RlEjQKBERhdGUYAiABKAsyJi5RdW90ZVJlc2VhcmNoLlNl",
            "cnZpY2UuU2hhcmUuVHlwZS5EYXRlIiUKE0VkaXRIb2xpZGF5UmVzcG9uc2US",
            "DgoGUmVzdWx0GAEgASgFIl0KGEVkaXRRdW90ZVNjaGVkdWxlUmVxdWVzdBJB",
            "CghTY2hlZHVsZRgBIAEoCzIvLlF1b3RlUmVzZWFyY2guU2VydmljZS5TaGFy",
            "ZS5UeXBlLlF1b3RlU2NoZWR1bGUiGwoZRWRpdFF1b3RlU2NoZWR1bGVSZXNw",
            "b25zZSJgChJHZXRTY2hlZHVsZVJlcXVlc3QSEgoKU2NoZWR1bGVJRBgBIAEo",
            "CRI2CgVRdW90ZRgCIAEoCzInLlF1b3RlUmVzZWFyY2guU2VydmljZS5TaGFy",
            "ZS5UeXBlLlF1b3RlIlgKE0dldFNjaGVkdWxlUmVzcG9uc2USQQoIU2NoZWR1",
            "bGUYASABKAsyLy5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuU2hhcmUuVHlwZS5R",
            "dW90ZVNjaGVkdWxlIpEBChxHZXRRdW90ZVNjaGVkdWxlTGlzdFJlc3BvbnNl",
            "Ei4KClVwZGF0ZVRpbWUYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0",
            "YW1wEkEKCFNjaGVkdWxlGAIgAygLMi8uUXVvdGVSZXNlYXJjaC5TZXJ2aWNl",
            "LlNoYXJlLlR5cGUuUXVvdGVTY2hlZHVsZTLUCAoPU2NoZWR1bGVTZXJ2aWNl",
            "EoMBCgpBZGRIb2xpZGF5EjkuUXVvdGVSZXNlYXJjaC5TZXJ2aWNlLlNjaGVk",
            "dWxlU2VydmljZS5FZGl0SG9saWRheVJlcXVlc3QaOi5RdW90ZVJlc2VhcmNo",
            "LlNlcnZpY2UuU2NoZWR1bGVTZXJ2aWNlLkVkaXRIb2xpZGF5UmVzcG9uc2US",
            "hgEKDVJlbW92ZUhvbGlkYXkSOS5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuU2No",
            "ZWR1bGVTZXJ2aWNlLkVkaXRIb2xpZGF5UmVxdWVzdBo6LlF1b3RlUmVzZWFy",
            "Y2guU2VydmljZS5TY2hlZHVsZVNlcnZpY2UuRWRpdEhvbGlkYXlSZXNwb25z",
            "ZRKQAQoLQWRkU2NoZWR1bGUSPy5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuU2No",
            "ZWR1bGVTZXJ2aWNlLkVkaXRRdW90ZVNjaGVkdWxlUmVxdWVzdBpALlF1b3Rl",
            "UmVzZWFyY2guU2VydmljZS5TY2hlZHVsZVNlcnZpY2UuRWRpdFF1b3RlU2No",
            "ZWR1bGVSZXNwb25zZRKTAQoOUmVtb3ZlU2NoZWR1bGUSPy5RdW90ZVJlc2Vh",
            "cmNoLlNlcnZpY2UuU2NoZWR1bGVTZXJ2aWNlLkVkaXRRdW90ZVNjaGVkdWxl",
            "UmVxdWVzdBpALlF1b3RlUmVzZWFyY2guU2VydmljZS5TY2hlZHVsZVNlcnZp",
            "Y2UuRWRpdFF1b3RlU2NoZWR1bGVSZXNwb25zZRKTAQoOVXBkYXRlU2NoZWR1",
            "bGUSPy5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuU2NoZWR1bGVTZXJ2aWNlLkVk",
            "aXRRdW90ZVNjaGVkdWxlUmVxdWVzdBpALlF1b3RlUmVzZWFyY2guU2Vydmlj",
            "ZS5TY2hlZHVsZVNlcnZpY2UuRWRpdFF1b3RlU2NoZWR1bGVSZXNwb25zZRKE",
            "AQoLR2V0U2NoZWR1bGUSOS5RdW90ZVJlc2VhcmNoLlNlcnZpY2UuU2NoZWR1",
            "bGVTZXJ2aWNlLkdldFNjaGVkdWxlUmVxdWVzdBo6LlF1b3RlUmVzZWFyY2gu",
            "U2VydmljZS5TY2hlZHVsZVNlcnZpY2UuR2V0U2NoZWR1bGVSZXNwb25zZRJj",
            "ChVHZXRTY2hlZHVsZVVwZGF0ZVRpbWUSLi5RdW90ZVJlc2VhcmNoLlNlcnZp",
            "Y2UuU2hhcmUuVHlwZS5FbXB0eVJlcXVlc3QaGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wEoYBCg9HZXRTY2hlZHVsZUxpc3QSLi5RdW90ZVJlc2VhcmNo",
            "LlNlcnZpY2UuU2hhcmUuVHlwZS5FbXB0eVJlcXVlc3QaQy5RdW90ZVJlc2Vh",
            "cmNoLlNlcnZpY2UuU2NoZWR1bGVTZXJ2aWNlLkdldFF1b3RlU2NoZWR1bGVM",
            "aXN0UmVzcG9uc2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::QuoteResearch.Service.Share.Type.TypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.EditHolidayRequest), global::QuoteResearch.Service.ScheduleService.EditHolidayRequest.Parser, new[]{ "Quote", "Date" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.EditHolidayResponse), global::QuoteResearch.Service.ScheduleService.EditHolidayResponse.Parser, new[]{ "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.EditQuoteScheduleRequest), global::QuoteResearch.Service.ScheduleService.EditQuoteScheduleRequest.Parser, new[]{ "Schedule" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.EditQuoteScheduleResponse), global::QuoteResearch.Service.ScheduleService.EditQuoteScheduleResponse.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.GetScheduleRequest), global::QuoteResearch.Service.ScheduleService.GetScheduleRequest.Parser, new[]{ "ScheduleID", "Quote" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.GetScheduleResponse), global::QuoteResearch.Service.ScheduleService.GetScheduleResponse.Parser, new[]{ "Schedule" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::QuoteResearch.Service.ScheduleService.GetQuoteScheduleListResponse), global::QuoteResearch.Service.ScheduleService.GetQuoteScheduleListResponse.Parser, new[]{ "UpdateTime", "Schedule" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EditHolidayRequest : pb::IMessage<EditHolidayRequest> {
    private static readonly pb::MessageParser<EditHolidayRequest> _parser = new pb::MessageParser<EditHolidayRequest>(() => new EditHolidayRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditHolidayRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayRequest(EditHolidayRequest other) : this() {
      quote_ = other.quote_ != null ? other.quote_.Clone() : null;
      date_ = other.date_ != null ? other.date_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayRequest Clone() {
      return new EditHolidayRequest(this);
    }

    /// <summary>Field number for the "Quote" field.</summary>
    public const int QuoteFieldNumber = 1;
    private global::QuoteResearch.Service.Share.Type.Quote quote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QuoteResearch.Service.Share.Type.Quote Quote {
      get { return quote_; }
      set {
        quote_ = value;
      }
    }

    /// <summary>Field number for the "Date" field.</summary>
    public const int DateFieldNumber = 2;
    private global::QuoteResearch.Service.Share.Type.Date date_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QuoteResearch.Service.Share.Type.Date Date {
      get { return date_; }
      set {
        date_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditHolidayRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditHolidayRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Quote, other.Quote)) return false;
      if (!object.Equals(Date, other.Date)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (quote_ != null) hash ^= Quote.GetHashCode();
      if (date_ != null) hash ^= Date.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (quote_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Quote);
      }
      if (date_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Date);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (quote_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quote);
      }
      if (date_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Date);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditHolidayRequest other) {
      if (other == null) {
        return;
      }
      if (other.quote_ != null) {
        if (quote_ == null) {
          Quote = new global::QuoteResearch.Service.Share.Type.Quote();
        }
        Quote.MergeFrom(other.Quote);
      }
      if (other.date_ != null) {
        if (date_ == null) {
          Date = new global::QuoteResearch.Service.Share.Type.Date();
        }
        Date.MergeFrom(other.Date);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (quote_ == null) {
              Quote = new global::QuoteResearch.Service.Share.Type.Quote();
            }
            input.ReadMessage(Quote);
            break;
          }
          case 18: {
            if (date_ == null) {
              Date = new global::QuoteResearch.Service.Share.Type.Date();
            }
            input.ReadMessage(Date);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditHolidayResponse : pb::IMessage<EditHolidayResponse> {
    private static readonly pb::MessageParser<EditHolidayResponse> _parser = new pb::MessageParser<EditHolidayResponse>(() => new EditHolidayResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditHolidayResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayResponse(EditHolidayResponse other) : this() {
      result_ = other.result_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditHolidayResponse Clone() {
      return new EditHolidayResponse(this);
    }

    /// <summary>Field number for the "Result" field.</summary>
    public const int ResultFieldNumber = 1;
    private int result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditHolidayResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditHolidayResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditHolidayResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditQuoteScheduleRequest : pb::IMessage<EditQuoteScheduleRequest> {
    private static readonly pb::MessageParser<EditQuoteScheduleRequest> _parser = new pb::MessageParser<EditQuoteScheduleRequest>(() => new EditQuoteScheduleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditQuoteScheduleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleRequest(EditQuoteScheduleRequest other) : this() {
      schedule_ = other.schedule_ != null ? other.schedule_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleRequest Clone() {
      return new EditQuoteScheduleRequest(this);
    }

    /// <summary>Field number for the "Schedule" field.</summary>
    public const int ScheduleFieldNumber = 1;
    private global::QuoteResearch.Service.Share.Type.QuoteSchedule schedule_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QuoteResearch.Service.Share.Type.QuoteSchedule Schedule {
      get { return schedule_; }
      set {
        schedule_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditQuoteScheduleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditQuoteScheduleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Schedule, other.Schedule)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (schedule_ != null) hash ^= Schedule.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (schedule_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Schedule);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (schedule_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Schedule);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditQuoteScheduleRequest other) {
      if (other == null) {
        return;
      }
      if (other.schedule_ != null) {
        if (schedule_ == null) {
          Schedule = new global::QuoteResearch.Service.Share.Type.QuoteSchedule();
        }
        Schedule.MergeFrom(other.Schedule);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (schedule_ == null) {
              Schedule = new global::QuoteResearch.Service.Share.Type.QuoteSchedule();
            }
            input.ReadMessage(Schedule);
            break;
          }
        }
      }
    }

  }

  public sealed partial class EditQuoteScheduleResponse : pb::IMessage<EditQuoteScheduleResponse> {
    private static readonly pb::MessageParser<EditQuoteScheduleResponse> _parser = new pb::MessageParser<EditQuoteScheduleResponse>(() => new EditQuoteScheduleResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EditQuoteScheduleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleResponse(EditQuoteScheduleResponse other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EditQuoteScheduleResponse Clone() {
      return new EditQuoteScheduleResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EditQuoteScheduleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EditQuoteScheduleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EditQuoteScheduleResponse other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class GetScheduleRequest : pb::IMessage<GetScheduleRequest> {
    private static readonly pb::MessageParser<GetScheduleRequest> _parser = new pb::MessageParser<GetScheduleRequest>(() => new GetScheduleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetScheduleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleRequest(GetScheduleRequest other) : this() {
      scheduleID_ = other.scheduleID_;
      quote_ = other.quote_ != null ? other.quote_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleRequest Clone() {
      return new GetScheduleRequest(this);
    }

    /// <summary>Field number for the "ScheduleID" field.</summary>
    public const int ScheduleIDFieldNumber = 1;
    private string scheduleID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ScheduleID {
      get { return scheduleID_; }
      set {
        scheduleID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Quote" field.</summary>
    public const int QuoteFieldNumber = 2;
    private global::QuoteResearch.Service.Share.Type.Quote quote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QuoteResearch.Service.Share.Type.Quote Quote {
      get { return quote_; }
      set {
        quote_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetScheduleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetScheduleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScheduleID != other.ScheduleID) return false;
      if (!object.Equals(Quote, other.Quote)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ScheduleID.Length != 0) hash ^= ScheduleID.GetHashCode();
      if (quote_ != null) hash ^= Quote.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ScheduleID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ScheduleID);
      }
      if (quote_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Quote);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ScheduleID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ScheduleID);
      }
      if (quote_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Quote);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetScheduleRequest other) {
      if (other == null) {
        return;
      }
      if (other.ScheduleID.Length != 0) {
        ScheduleID = other.ScheduleID;
      }
      if (other.quote_ != null) {
        if (quote_ == null) {
          Quote = new global::QuoteResearch.Service.Share.Type.Quote();
        }
        Quote.MergeFrom(other.Quote);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ScheduleID = input.ReadString();
            break;
          }
          case 18: {
            if (quote_ == null) {
              Quote = new global::QuoteResearch.Service.Share.Type.Quote();
            }
            input.ReadMessage(Quote);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetScheduleResponse : pb::IMessage<GetScheduleResponse> {
    private static readonly pb::MessageParser<GetScheduleResponse> _parser = new pb::MessageParser<GetScheduleResponse>(() => new GetScheduleResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetScheduleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleResponse(GetScheduleResponse other) : this() {
      schedule_ = other.schedule_ != null ? other.schedule_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetScheduleResponse Clone() {
      return new GetScheduleResponse(this);
    }

    /// <summary>Field number for the "Schedule" field.</summary>
    public const int ScheduleFieldNumber = 1;
    private global::QuoteResearch.Service.Share.Type.QuoteSchedule schedule_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::QuoteResearch.Service.Share.Type.QuoteSchedule Schedule {
      get { return schedule_; }
      set {
        schedule_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetScheduleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetScheduleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Schedule, other.Schedule)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (schedule_ != null) hash ^= Schedule.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (schedule_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Schedule);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (schedule_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Schedule);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetScheduleResponse other) {
      if (other == null) {
        return;
      }
      if (other.schedule_ != null) {
        if (schedule_ == null) {
          Schedule = new global::QuoteResearch.Service.Share.Type.QuoteSchedule();
        }
        Schedule.MergeFrom(other.Schedule);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (schedule_ == null) {
              Schedule = new global::QuoteResearch.Service.Share.Type.QuoteSchedule();
            }
            input.ReadMessage(Schedule);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetQuoteScheduleListResponse : pb::IMessage<GetQuoteScheduleListResponse> {
    private static readonly pb::MessageParser<GetQuoteScheduleListResponse> _parser = new pb::MessageParser<GetQuoteScheduleListResponse>(() => new GetQuoteScheduleListResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetQuoteScheduleListResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::QuoteResearch.Service.ScheduleService.ScheduleServiceReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteScheduleListResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteScheduleListResponse(GetQuoteScheduleListResponse other) : this() {
      updateTime_ = other.updateTime_ != null ? other.updateTime_.Clone() : null;
      schedule_ = other.schedule_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetQuoteScheduleListResponse Clone() {
      return new GetQuoteScheduleListResponse(this);
    }

    /// <summary>Field number for the "UpdateTime" field.</summary>
    public const int UpdateTimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp updateTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp UpdateTime {
      get { return updateTime_; }
      set {
        updateTime_ = value;
      }
    }

    /// <summary>Field number for the "Schedule" field.</summary>
    public const int ScheduleFieldNumber = 2;
    private static readonly pb::FieldCodec<global::QuoteResearch.Service.Share.Type.QuoteSchedule> _repeated_schedule_codec
        = pb::FieldCodec.ForMessage(18, global::QuoteResearch.Service.Share.Type.QuoteSchedule.Parser);
    private readonly pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.QuoteSchedule> schedule_ = new pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.QuoteSchedule>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::QuoteResearch.Service.Share.Type.QuoteSchedule> Schedule {
      get { return schedule_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetQuoteScheduleListResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetQuoteScheduleListResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(UpdateTime, other.UpdateTime)) return false;
      if(!schedule_.Equals(other.schedule_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (updateTime_ != null) hash ^= UpdateTime.GetHashCode();
      hash ^= schedule_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (updateTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(UpdateTime);
      }
      schedule_.WriteTo(output, _repeated_schedule_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (updateTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateTime);
      }
      size += schedule_.CalculateSize(_repeated_schedule_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetQuoteScheduleListResponse other) {
      if (other == null) {
        return;
      }
      if (other.updateTime_ != null) {
        if (updateTime_ == null) {
          UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        UpdateTime.MergeFrom(other.UpdateTime);
      }
      schedule_.Add(other.schedule_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (updateTime_ == null) {
              UpdateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(UpdateTime);
            break;
          }
          case 18: {
            schedule_.AddEntriesFrom(input, _repeated_schedule_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
